language: go

go:
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get github.com/docopt/docopt-go
  - go get github.com/PuerkitoBio/goquery
  - go get github.com/Sirupsen/logrus

script:
  - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN

env:
  global:
    secure: "OEFJ2jmTPx7LI3bvTdg2g2Not1PAFTYSBojun+XQyaeKRKO05CPn2mEdFAhtmEe9BwsXqk/TcidlFtAJDv1kS0r1J3wblGiYt6o/dRMmeHVG216udLxtABgKbvXt/Awz9PUD5n/82oZ+kdTc/Qk7GqjjiYhflcbs9dpJ00boWTXw2m6a6yK37RcKlyMBMZH1sHl3747WcaD1yqm+abciF0c9UfGU61fy9Up/M9bPWii7+S9V9jaHcHbqPDXmMLYWamFfWSE2+WMkvL05yuTt7KNW0VSPyYppCthkQyJ9CNa9zCIA75EyEwX/HRoDRIV75CyD1/Nzf9afHxzfZKLGa4o/uQCHNKiHL82kwmuPHvtWaC7gwN1cJ0cU46FfdhL7m4OcCrVOwDBd7cjWp/GH/dAKh8/BQIHyDL0PMuaaWFOO0GJYU6HQqWO/DsdtE4KXUFtHKzxOkfYrnHsucU9d730DFzPbMqUrub613EBxZbdp9td/DMsxNFpb3JNxqK9mbDhO+AjfHiy/yvWQuAmbjZIZkUfcCpTPrxeXngypkpjp40bkTp+lJlS8RyPP8rDO34eJDdzE90hIEvqc+d+Otv8gH7eUKXMqcRnMOdr/iIhfiF7dxUiznwMNkduu/ZOfvFg6YwdA9VJMh/vTUUZXx4SqM/VwEjuuUh3zMEdoExw="
